### ISSUE TITLE
Tps issues

### ISSUE THREAD

**Issue by galoti** [Aquerr/ChestRefill#10]
## Environment

* **Sponge Version:** spongeforge-1.12.2-2768-7.1.6-RC3616

* **Plugin Version:** ChestRefill-1.12.2-1.5.0-pre

## What happens?

   My timings report shows that chestrefill cause lag spikes. I have 20 Chests with auto refill disabled  ( "time": 0 ) and the options "replace-existing-items", "hidden-if-no-items" set to true. Hiding block = minecraft:packed_ice

## Expected result

No tps issues

## More information

Timings: https://timings.aikar.co/?id=459e2232734e43d2ae557d7a903ae1ee

**Comment by Aquerr** [comment]
@galoti Maybe I am reading timings wrongly but I can't see anything wrong with Chest Refill there.

**Virtual Chest** is having much bigger timings than Chest Refill. Are you sure it is the Chest Refill problem?

**Comment by galoti** [comment]
I forgot to say it's normal now. Just updated my Spongeforge version

**Comment by Aquerr** [comment]
Okay, then this issue can be closed right?

**Comment by galoti** [comment]
Yes, this issue can be closed. I also have a feature suggestion: The possibility to configure messages to each refillable container when the refill occurs (individually) and when someone opens for the first time after refill.

**Comment by Aquerr** [comment]
Open a new **issue/feature request** for it. Then we will see what can be done for it. :)
