### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by galoti** [Aquerr/ChestRefill#12]
Possibility to configure messages to each refillable container when the refill occurs (individually) and when someone opens for the first time after refill.

**Comment by Aquerr** [comment]
So basically, this feature request is about two things. 1. Printing a message when refill occurs (currently nothing is sent to the chat/console if chest is refilled). 2. Printing some kind of message when someone opens refillable container for the first time? Am I right?

**Comment by galoti** [comment]
Yes, exactly

**Comment by Aquerr** [comment]
Ok! I will add it to my TO DO list and see what can be done for it!
