### ISSUE TITLE
I love it but.......

### ISSUE THREAD

**Issue by Nalle3** [Aquerr/ChestRefill#13]
When you restart your server all chest's reset so every time i reset server i must again type "/cr c" and yeah. Please fix that!!

**Comment by Aquerr** [comment]
Shit, didn't know such thing was happening. I will try to fix this asap.

**Comment by Aquerr** [comment]
@Nalle3 Could you please check if there are any errors in the console when your server is restarting after creating some containers?

**Comment by Nalle3** [comment]
No errors i see it's a common issue. I deleted all other plugins but still same..

**Comment by Aquerr** [comment]
@Nalle3 I just tested the latest version of Chest Refill on my own server and it is working fine. Are you sure you are not getting any errors in the console? Or maybe you store some advanced items in your chests that the plugin cannot translate? It is really strange that it is working for me but not for you.

Tell me what version of Minecraft, SpongeForge and Chest Refill you are using.
