### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ziceptor** [Aquerr/ChestRefill#5]
https://gist.github.com/ziceptor/970c6bb077f92590d1b35b1644815ee0

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar
ChestRefill-1.12.2-1.0.0.jar

**Comment by Aquerr** [comment]
@ziceptor There may be an issue with items you want to regenerate.

Could you please tell me what items did you put in the chest?

**Comment by ziceptor** [comment]
torch

**Comment by Aquerr** [comment]
I have tested it now with only one torch in the chest and it works very good.

Is it a normal minecraft torch that you are trying to regenerate?

**Comment by ziceptor** [comment]
yes

**Comment by ziceptor** [comment]
I'll run more tests when I have free time.

**Comment by Aquerr** [comment]
Is this still occurring?

**Comment by ziceptor** [comment]
I'll check later. Maybe it's connected to https://github.com/Aquerr/ChestRefill/issues/6
