### ISSUE TITLE
NoSuchElementException: No value present

### ISSUE THREAD

**Issue by ziceptor** [Aquerr/ChestRefill#6]
Just archery. The chests there.
https://gist.github.com/ziceptor/98ad67bea59d8f4bb5c8b60413ce69ad

**Comment by ziceptor** [comment]
forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar
ChestRefill-1.12.2-1.2.0.jar

**Comment by Aquerr** [comment]
How did this happen? You just right-clicked a normal chest?

**Comment by ziceptor** [comment]
No. I shot from a bow by the skeleton.

**Comment by Aquerr** [comment]
Oh, okay, that's strange. I will look deeper at it.

**Comment by Aquerr** [comment]
I know what is the problem... a fix will be added in the next version.
