### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ziceptor** [Aquerr/ChestRefill#7]
...  with enchanted items.

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2990.jar
ChestRefill-1.12.2-1.2.1.jar

In the console error. At this point, I cannot provide a log.

**Comment by Aquerr** [comment]
I will look at this when I will have some free time :)

**Comment by Aquerr** [comment]
It works with **spongeforge-1.12.2-2611-7.1.0-BETA-3002**

**Comment by ziceptor** [comment]
ChestRefill-1.12.2-1.2.1.jar or should I build a new jar file?

**Comment by Aquerr** [comment]
ChestRefill-1.12.2-1.2.1.jar

**Comment by ziceptor** [comment]
Thank you for your time. I'll check when I have time. Close issue.
