### ISSUE TITLE
Suggestion: select random item(s) to refill container with

### ISSUE THREAD

**Issue by Shmeeb** [Aquerr/ChestRefill#8]
It would be very nice if there was an option to refill a container with one or more randomly selected items.

Love your plugin, thanks!

**Comment by Aquerr** [comment]
I added a code for this 2 days ago 😃. A release with this feature should arrive this week.

Each item will have a percentage chance to show up in the chest. You will be able to configure it as you want. :)

**Comment by Aquerr** [comment]
Released in 1.3.0

If you will have any ideas in the future on what could be improved/added then feel free to post them as **Issues** like this one. :)

I am closing this issue.
