### ISSUE TITLE
Force Refill Chests? [Feature Request]

### ISSUE THREAD

**Issue by KhaozFrost** [Aquerr/ChestRefill#9]
would it be possible to add a command or something to force reset chests that dont have anything in them? I see this plugin very useful for creating something like a hunger games kinda thing so would def need a way to regenerate the stuff after 'a game' was to end.

**Comment by Aquerr** [comment]
Sure thing I can add it. :)

Should this command work like other commands? You need to type in the command and click the chest? Or just type chest’s coords/name without clicking it?

**Comment by KhaozFrost** [comment]
I'd say without clicking it. if it automatically was to store the chest's coords in like config file upon creating or something you might not even have to type the chest's coords or have it as an optional argument where you could use coords to regen specific chests but if you dont use the argument it would regen all of them.

**Comment by Aquerr** [comment]
That’s what I thought. No clicking needed.

Good idea with the optional thing. I haven’f thought about forcing refill on every chest at the same time but I like the idea.

I will try to add it as soon as possible. :)

I just need to think a little bit more about writing coords, as they may be difficult to write sometime. I think it would be easier to give the chest a name and then type it in the command but I will think about it more. 😛

**Comment by Aquerr** [comment]
Ah, well, I forgot closing this. This feature has been added in the latest version! :)
